---
name: foo
domain: domain.com
knife_ec2_flags:
    availability-zone: us-east-1d
    ebs-size: 30
    environment: testing
    private-ip-address: X.X.X.X
    run-list: recipe[recipe1]
    security-group-ids: sg-12345678,sg-abcdef01
    subnet: subnet-12345678